// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBumYDW7Ele-2vig8okcKD5AZ3CQYXkuWw',
    appId: '1:309082770033:web:9274c4658526a6e49069d0',
    messagingSenderId: '309082770033',
    projectId: 'fluttertestproject-245c8',
    authDomain: 'fluttertestproject-245c8.firebaseapp.com',
    storageBucket: 'fluttertestproject-245c8.appspot.com',
    measurementId: 'G-367N77D4LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAmcSN0_cok5c9AH8hGt9ofG8RMfEuXDc',
    appId: '1:309082770033:android:87afb2ecd686cf989069d0',
    messagingSenderId: '309082770033',
    projectId: 'fluttertestproject-245c8',
    storageBucket: 'fluttertestproject-245c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAefpGPI-fcT-CJAG11ZIdroegey1oIDPk',
    appId: '1:309082770033:ios:3879ed5516c1b3e89069d0',
    messagingSenderId: '309082770033',
    projectId: 'fluttertestproject-245c8',
    storageBucket: 'fluttertestproject-245c8.appspot.com',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAefpGPI-fcT-CJAG11ZIdroegey1oIDPk',
    appId: '1:309082770033:ios:3879ed5516c1b3e89069d0',
    messagingSenderId: '309082770033',
    projectId: 'fluttertestproject-245c8',
    storageBucket: 'fluttertestproject-245c8.appspot.com',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBumYDW7Ele-2vig8okcKD5AZ3CQYXkuWw',
    appId: '1:309082770033:web:4b6d0202f6518fd89069d0',
    messagingSenderId: '309082770033',
    projectId: 'fluttertestproject-245c8',
    authDomain: 'fluttertestproject-245c8.firebaseapp.com',
    storageBucket: 'fluttertestproject-245c8.appspot.com',
    measurementId: 'G-MQRNVFTS63',
  );
}
